
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '../contexts/authContext'
import ClientNavbar from '../components/clientNavBar/page'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}




export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} scroll-smooth antialiased`}
      >
        {/* 1. Header / Menu */}
        <ClientNavbar />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
