import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '../components/providers/AuthProvider'
import ClientNavbar from '../components/clientNavBar/page'
import { Toaster } from 'react-hot-toast'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} scroll-smooth antialiased`}
      >
        {/* 1. Header / Menu */}
        <ClientNavbar />
        <AuthProvider>
          {children}
          <Toaster
            position='top-right'
            toastOptions={{
              duration: 4000,
              style: {
                background: '#363636',
                color: '#fff'
              },
              success: {
                duration: 3000,
                theme: {
                  primary: '#4ade80'
                }
              },
              error: {
                duration: 5000,
                theme: {
                  primary: '#ef4444'
                }
              }
            }}
          />
        </AuthProvider>
      </body>
    </html>
  )
}
